### ISSUE TITLE
Permission error somewhy

### ISSUE THREAD

**Issue by PSHacks** [WheteThunger/VehicleDeployedLocks#6]
Hi. There is a bug (sort of), I can put lock on any vehicle, but on "motorbike_sidecar.prefab" I've got error "Generic.Error.NoPermission"..

**Comment by WheteThunger** [comment]
Working for me. I tested with `vehicledeployedlocks.codelock.motorbike.sidecar` and also separately with `vehicledeployedlocks.codelock.allvehicles`.
