### ISSUE TITLE
When the server is restarted, the scaled entities disappear.

### ISSUE THREAD

**Issue by little-method** [WheteThunger/VehicleDeployedLocks#7]
I have developed a plugin to add a searchlight to a RHIB using [Entity Scale Manager](https://umod.org/plugins/entity-scale-manager).
I then installed this plugin to lock the boat.
However, when I restart the server, the searchlight disappears.

Is this plugin incompatible with Entity Scale Manager?

**Comment by WheteThunger** [comment]
I can't think of any reason why they would be incompatible. Your search light and sphere entity are simply additional children of the RHIB, alongside the lock. Have you checked if the search light disappears when the vehicle is not locked?

There could be multiple reasons why the search light is disappearing. One possibility is that you haven't destroyed the GroundWatch/DestroyOnGroundMissing components from it. On server restart, you need to find and re-destroy those components as Rust will have recreated them when recreating the search light from save.

**Comment by little-method** [comment]
Sorry, I used `Entity Scale Manager` incorrectly.
This issue is closed.
